In [21]:
import pandas as pd
import numpy as np
from scipy import stats

abalone = pd.read_csv("data/abalone_sub.csv")
hr = pd.read_csv("data/health_promo_hr.csv")

x = abalone.viscera[abalone.gender == "M"]
y = abalone.viscera[abalone.gender == "F"]

t_out = stats.ttest_ind(x,y)
ci_95 = t_out.confidence_interval()
print(f"""
Pvalue for the test is {t_out.pvalue:.3f}
Test statistics {t_out.statistic:.3f}
95% CI: {tuple(list(ci_95))}
""")

Pvalue for the test is 0.365
Test statistics 0.910
95% CI: (np.float64(-0.02336286934687589), np.float64(0.06294286934687596))

In [ ]:
abalone.groupby("gender").describe()

       viscera
         count     mean       std    min       25%    50%       75%    max
gender
F         50.0  0.28241  0.108707  0.095  0.201250  0.275  0.365125  0.575
M         50.0  0.30220  0.108746  0.040  0.253125  0.310  0.348750  0.638

In [7]:
abalone.groupby("gender").skew()

         viscera
gender
F       0.418761
M       0.256046

In [19]:
for i,df in abalone.groupby('gender'):
    print(f"{df.gender.iloc[0]}: {df.viscera.kurt():.4f}")

F: -0.1390
M: 1.4220

In [17]:
stats.shapiro(x)

ShapiroResult(statistic=np.float64(0.9677872659314101), pvalue=np.float64(0.1878490793650714))

In [18]:
stats.shapiro(y)

ShapiroResult(statistic=np.float64(0.9778353511621297), pvalue=np.float64(0.4647245165728363))

In [20]:
stats.mannwhitneyu(x,y)

MannwhitneyuResult(statistic=np.float64(1415.5), pvalue=np.float64(0.25527909580927854))

In [ ]:
wsr_out = stats.wilcoxon(hr.baseline, hr.after5, correction = True, method = "approx")

print(f"""
Test Statistics: {wsr_out.statistic:.3f}
P value: {wsr_out.pvalue:.5f}
""")

Test Statistics: 0.000
P value: 0.00251

: